<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Cauldron.Persistence</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Dapper" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../shared/Cauldron.Abstractions/Cauldron.Abstractions.csproj" />
  </ItemGroup>
</Project>
